#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  \#1cc5a6
bspc config normal_border_color   \#44475a

##RULES
bspc rule -a zoom state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Nl.hjdskes.gcolor3 state=floating

#autostart
killall picom
sleep 0.1 && picom --daemon & #compositor
nitrogen --restore & #wallpaper setter
killall polybar
sleep 0.1 && polybar & #status bar
#killall blueman-applet
#sleep 0.1 && blueman-applet & #bluetooth-management
killall nm-applet
sleep 0.7 && nm-applet & #network-management
killall polkit-gnome-authentication-agent-1
sleep 0.1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & #polkit-1 agent
killall cbatticon
sleep 0.8 && cbatticon -n -u 60 & #battery systray icon
killall volumeicon
sleep 5 && volumeicon & #volume systray icon

#configs
xinput set-prop "SYNA2BA6:00 06CB:CE2D Touchpad" "libinput Tapping Enabled" 1
#xinput set-prop 8 "libinput Accel Speed" -0.5 #Mouse at home
xinput set-prop "2.4G Mouse" "libinput Accel Speed" -0.7 #wireless mouse
