#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  \#c678dd
bspc config normal_border_color   \#44475a

##RULES
bspc rule -a Pycalendar.py state=floating rectangle=600x400+3+36
bspc rule -a Conky border=off state=floating locked=off layer=below
bspc rule -a Skype state=floating
bspc rule -a steam state=floating
bspc rule -a zoom state=floating

#autostart
killall picom
sleep 1 && picom --daemon & #compositor
nitrogen --restore & #wallpaper setter
killall conky
sleep 1 && conky &
killall polybar
sleep 1 && polybar & #status bar
killall nm-applet
sleep 1 && nm-applet & #network-management
killall polkit-gnome-authentication-agent-1
sleep 1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & #polkit-1 agent


#configs
xinput set-prop "SYNA2BA6:00 06CB:CE2D Touchpad" "libinput Tapping Enabled" 1
#xinput set-prop 8 "libinput Accel Speed" -0.5 #Mouse at home
xinput set-prop "2.4G Mouse" "libinput Accel Speed" -0.7 #wireless mouse
